### ISSUE TITLE
"dry-run: true" still deployed a new helm chart

### ISSUE THREAD

**Issue by jpds** [ipedrazas/drone-helm#71]
I have a simple pipeline:

```
pipeline:
  helm_deploy:
    image: quay.io/ipedrazas/drone-helm
    skip_tls_verify: true
    chart: stable/prometheus
    update_dependencies: false
    release: prometheus
    namespace: production-prometheus
    dry-run: true
    secrets: [ api_server, kubernetes_token ]
    when:
      branch: [master]
```

Interestingly, when this ran, it actually deployed prometheus, into that namespace.

**Comment by minhdanh** [comment]
I think this is because the actual env var passed to drone-helm container by Drone is `PLUGIN_DRY-RUN`, not `PLUGIN_DRY_RUN`.

**Comment by ipedrazas** [comment]
Have you tried this?

```
pipeline:
  helm_deploy:
    image: quay.io/ipedrazas/drone-helm
    skip_tls_verify: true
    chart: stable/prometheus
    update_dependencies: false
    release: prometheus
    namespace: production-prometheus
    dry_run: true
    secrets: [ api_server, kubernetes_token ]
    when:
      branch: [master]
```
